# Use an official Python runtime as a parent image
FROM python:3.10-slim
# Use the CUDA 12.2.0 runtime image as the base
# FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8

# Set the working directory in the container
WORKDIR /flask_app

# Copy the current directory contents into the container at /flask_app
COPY . /flask_app

# Install any needed system dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Ensure the /flask_app/DATA directory exists and has the correct permissions
RUN mkdir -p /flask_app/DATA && chmod -R 777 /flask_app/DATA

# Make port 8001 available to the world outside this container
EXPOSE 8001

# Define environment variable
ENV FLASK_APP=3DObjectRetrievalAPI_v1.py

# Run the Flask application
CMD ["flask", "run", "--host=0.0.0.0", "--port=8000"]
